package com.manning.apisecurityinaction.rules;

import com.manning.apisecurityinaction.controller.DroolsAccessController.*;
import com.manning.apisecurityinaction.controller.ABACAccessController.Decision;

global Decision decision;

rule "deny moderation outside office hours"
    when
        Action( this["method"] == "DELETE" )
        Environment( this["timeOfDay"].hour < 9
            || this["timeOfDay"].hour > 17 )
    then
        decision.deny();
end